### ISSUE TITLE
Defining DynamoDB batch-get-item key value

### ISSUE THREAD

**Issue by daveliepmann** [mcohen01/amazonica#240]
I had some trouble with the DynamoDB `batch-get-item` example in the README. I'm not sure if I'm missing something, if the example is in error, or if there's a bug.

For reference, the example is:

```
(batch-get-item
  cred
  :return-consumed-capacity "TOTAL"
  :request-items {
  "TestTable" {:keys [{"id"   {:s "foobar"}
                       "date" {:n 3172671}}
                      {"id"   {:s "foo"}
                       "date" {:n 123456}}]
               :consistent-read true
               :attributes-to-get ["id" "text" "column1"]}})
```

Using that syntax, I tried:
```
(batch-get-item :request-items {"my-table" {:keys [{"id" {:s "uuid-abcd-1234"}}]}})
```
This throws *clojure.lang.PersistentArrayMap cannot be cast to com.amazonaws.services.dynamodbv2.model.AttributeValue*. Somehow `{:s "uuid-abcd-1234"}` is not recognized as an attribute-value parameter, so I tried with a plain String:

```
(batch-get-item :request-items {"my-table" {:keys [{"id" "uuid-abcd-1234"}]}})
```
This throws *java.lang.String cannot be cast to com.amazonaws.services.dynamodbv2.model.AttributeValue*, which is odd, since I thought that was a [known constructor](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/AttributeValue.html#AttributeValue-java.lang.String-). I tried a few other variations, but no Clojure structure I could think up satisfied AWS. Yet:

```
(batch-get-item :request-items {"my-table" {:keys [{"id" (com.amazonaws.services.dynamodbv2.model.AttributeValue. "uuid-abcd-1234")}]}})
```
...works. Is this expected behavior?

**Comment by mcohen01** [comment]
I think the issue here is one of [nested](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/BatchGetItemRequest.html#setRequestItems-java.util.Map-) generic Java [collections](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/KeysAndAttributes.html#setKeys-java.util.Collection-), which this library always has a bit of trouble with in certain places. You should be able to simply pass raw strings with 0.3.76 instead of manually creating `AttributeValues`.

**Comment by daveliepmann** [comment]
Awesome, that resolved it. Thanks!
