### ISSUE TITLE
Some attributes can't be specified as strings?

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#250]
Evaluating this:

```
(#'amazonica.aws.ec2/describe-vpc-attribute :vpc-id  "vpc-xyzzy" :attribute "EnableDnsHostnames")
```

I get the following exception:

```
com.amazonaws.services.ec2.model.AmazonEC2Exception: Value (EnableDnsHostnames) for parameter attribute is invalid. Unknown attribute. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: iddqd)
```

"EnableDnsHostnames" is a valid name in the com.amazonaws.services.ec2.model.VpcAttributeName
enum.

**Comment by mcohen01** [comment]
`enableDnsHostnames` and `enableDnsSupport` are the string representations.... ¯\_(ツ)_/¯

**Comment by lvh** [comment]
Womp; thanks! Is that a general rule? I followed from `describe-vpc-attribute` to  the `describeVpcAttribute` method, to `DescribeVpcAttributeRequest`, to the `VpcAttributeName` enum, which has two values: `EnableDnsHostnames` and `EnableDnsSupport`. I was expecting this to work like `VpcAttributeName.valueOf`.

**Comment by mcohen01** [comment]
The problem is that `describe-vpc-attribute` is overloaded, one form with the enum argument, the other with the String. Amazonica resolves strings to enums case insensitively, but in this case it can't, because when you pass the string it finds a method whose signature matches exactly on that, and then it's down to the AWS Java code resolving to the enum.

**Comment by lvh** [comment]
BLAAARGH https://github.com/aws/aws-sdk-java/blob/8b2d07337f838a75b4275e8a5eb89f035ff0f06d/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/VpcAttributeName.java#L20-L21

I see what you mean now. Thanks! That was silly.
