### ISSUE TITLE
amazonica.aws.s3/get-object does not close the S3Object

### ISSUE THREAD

**Issue by jarppe** [mcohen01/amazonica#266]
Getting information using `amazonica.aws.s3/get-object` from multiple S3 objects causes an
`com.amazonaws.SdkClientException` exception with message "Unable to execute HTTP request: Timeout waiting for connection from pool".

It seems that the `S3Object` returned by `com.amazonaws.services.s3.AmazonS3Client/getObject`
holds an HTTP connection until it is explicitly closed (the `S3Object` implements `java.io.Closeable`). Once the HTTP connection pool is exhausted the I get the exception.

**Comment by mcohen01** [comment]
Yep, you are responsible for closing the stream yourself. If you're using the method that returns an `S3Object`, rather the [safer method](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#getObject-com.amazonaws.services.s3.model.GetObjectRequest-java.io.File-) that simply writes to a file and returns `ObjectMetadata`, presumably it's because you want to do something with the returned input stream, amazonica can't close it.

**Comment by eigenhombre** [comment]
We lost a day to this. It would be nice if this gotcha would be documented. Could we help with that?

**Comment by mcohen01** [comment]
"We lost a day to this."

That sucks, sorry to hear that.

"Could we help with that?"

Absolutely. You could add a note in the S3's example section of the readme.
If you're really feeling altruistic you could add a hook to print some
warning to the console. See the sqs namespace for an example.

**Comment by eigenhombre** [comment]
PR made (https://github.com/mcohen01/amazonica/pull/301) .. thanks
