### ISSUE TITLE
s3/list-next-batch-of-ojbects - IllegalArgumentException The parameter previousObjectListing must be specified.

### ISSUE THREAD

**Issue by ruseel** [mcohen01/amazonica#289]
Hi.

I am trying to call s3/list-next-batch-of-ojbects, but It raises
```
IllegalArgumentException The parameter previousObjectListing must be specified.
```

```
(require 'amazonica.aws.s3)
(require 'amazonica.core)
(amazonica.core/defcredential (get cred "aws.access_key_id") (get cred "aws.secret_access_key")
      "http://s3-ap-northeast-1.amazonaws.com")
(def lo (amazonica.aws.s3/list-objects {:bucket-name "b" :prefix "p"}))
(amazonica.aws.s3/list-next-batch-of-objects lo)
```

**Comment by ruseel** [comment]
code from `TheClimateCorporation`

https://github.com/TheClimateCorporation/S3DistVersions/blob/master/src/s3_dist_versions/s3.clj#L55

didn't work either.

**Comment by mcohen01** [comment]
Unfortunately the lack of a [no-arg constructor](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ListNextBatchOfObjectsRequest.html#ListNextBatchOfObjectsRequest-com.amazonaws.services.s3.model.ObjectListing-) is the problem here. I'm not sure there's an easy fix for this....
