### ISSUE TITLE
sts get-caller-identity doesn't accept credentials map

### ISSUE THREAD

**Issue by darrensony** [mcohen01/amazonica#306]
Example
---------
```
(ns example
  (:require [amazonica.aws.securitytoken :refer [get-caller-identity]]))

(get-caller-identity {:access-key "foo" :secret-key "bar"})
```

Result
-------
```
IllegalArgumentException Could not determine best method to invoke for get-caller-identity 
using arguments ({:access-key "foo", :secret-key "bar"})  
amazonica.core/intern-function/fn--5909 (core.clj:918)
```

I tried to find the right mix of java interop magic to manually create the appropriate credentials class, but I couldn't work it out.

I can't use _defcredential_, because I'm connecting to multiple AWS Accounts and Regions at the same time.

Thanks in advance
Darren

PS: This is a great library! Thanks for all your work.

**Comment by mcohen01** [comment]
I haven't looked at the version history of `AWSSecurityTokenServiceClient` but I'm pretty sure at some point in the past these methods like `getCallerIdentity()` that essentially don't take any arguments, they used to actually be no-arg java methods, rather than taking a subclass of `AmazonWebServiceRequest` that has no required setters, sometimes even, as in this case, literally no setters on the subclass. Unfortunately, now you have to pass an empty map that will get coerced into a `GetCallerIdentityRequest`. Every few months this pattern of bug gets reported here so there's some room to improve the library to handle these cases, or at least provide more informative error messages. 

```clj
(get-caller-identity {:access-key "foo" :secret-key "bar"} {})
```
will probably work for you, though I have not tried it...

**Comment by darrensony** [comment]
Unfortunately that doesn't work. Same error.

IllegalArgumentException Could not determine best method to invoke for get-caller-identity using arguments ({:access-key "foo", :secret-key "bar"} {})  amazonica.core/intern-function/fn--5909 (core.clj:918)

**Comment by mcohen01** [comment]
one nasty workaround until this gets resolved is to pass garbage in the map:
`(get-caller-identity {:access-key "foo" :secret-key "bar"} {:foo "bar"})`

**Comment by darrensony** [comment]
That works! Thanks. Feel free to close this ticket if you like.

Adding this just for googlefood:

```
; workaround: Amazonica, How to call get-caller-identity with credentials
; Add a second, non-empty map to the call. Values don't matter.

(ns example
  (:require [amazonica.aws.securitytoken :refer [get-caller-identity]]))


(let [cred  {:access-key "foo" :secret-key "bar"}]
  (get-caller-identity cred {:this-makes "it work"}))

; => {:user-id "AID..."
;     :account "123456789012"
;     :arn "arn:aws:iam::123456789012:/user/something"}
```
