### ISSUE TITLE
Help for writing the google adword api lib in clojure 

### ISSUE THREAD

**Issue by dupuchba** [mcohen01/amazonica#334]
Hello the amazonica team,

First, thanks for your work, I really learned a lot from the code.

Here is my question :
I'd like to use the [Google Adwords API](https://developers.google.com/adwords/api/docs/reference/v201708/AccountLabelService) in clojure.
The GAd-API provide a java client which is 1) horrible to use in Java 2) maybe even worst in clojure.

I'd like to know if you have any advices from your experience of amazonica to write a Java => CLJ wrapper by using reflection, marshall... I really don't know where to start.

Thanks a lot

**Comment by mcohen01** [comment]
The Adwords Java client looks like it's an ancient Axis 1.x generated client. It's been a long time since I have seen an Axis client, and I don't remember if it was based around JavaBeans. If so, there are many bits you could lift from here, if not, I can't really offer any advice off the top of my head. I only remember what a steaming pile of dogshit Axis was, so I'm afraid I am rather pessimistic about the possibilities here. But then again, it is a generated api, so you ought to be able to generate a clojure client on top of that, it just might not be as easy to do as working with Amazon's Java client. But if you can do it you'd be saving a lot of people a lot of pain! (Can't believe this is what Google offers Java programmers as an interface to their bread and butter application.....)

**Comment by dupuchba** [comment]
Thank's @mcohen01 , I'll take a look at axis generated client.

But indeed, you're right, GA-APIs are generated and there might/must be a better way for clojure dev to work with it.
